version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - symfony_net

  php:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - postgres

  php-worker:
    build:
      context: .
      dockerfile: Dockerfile.php-worker
    container_name: php-worker
    command: [ "sleep", "infinity" ]  # Command to keep the container running
    volumes:
      - ./:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5423"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - symfony_net

networks:
  symfony_net:
      driver: bridge