# Start from a PHP base image
FROM php:8.3-cli

# Install system dependencies
RUN apt-get update && \
        apt-get install -y \
        git \
        unzip \
        libpq-dev \
        && docker-php-ext-install pdo_pgsql

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html
